x-node: &node
  build:
    context: .
    dockerfile: docker/node/Dockerfile
    target: base
    args:
      - "UID=${UID:-1000}"
      - "GID=${GID:-1000}"
  volumes:
    - .:/var/www
  working_dir: /var/www/
  env_file:
    - .env
  networks:
    - wp-dev

services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - wp-dev

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: development
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - .:/var/www
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - wp-dev

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: db
      MARIADB_DATABASE: db
      MARIADB_USER: db
      MARIADB_PASSWORD: db
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-pdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - wp-dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    networks:
      - wp-dev

  redis:
    image: redis:8.0-alpine
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - wp-dev

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - wp-dev

  node:
    <<: *node
    tty: true
    stdin_open: true

  frontend:
    <<: *node
    command: sh -c "pnpm install && pnpm run -r start"
    ports:
      - "5173:5173" # skin theme vite port

volumes:
  db_data:
  redis_data:
  minio_data:

networks:
  wp-dev:
