services:
  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      - wp-dev
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: development
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - .:/var/www
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - wp-dev

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: db
      MARIADB_DATABASE: db
      MARIADB_USER: db
      MARIADB_PASSWORD: db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-dev
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-pdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  workspace:
    build:
      context: .
      dockerfile: docker/workspace/Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - .:/var/www
    env_file:
      - .env
    tty: true
    stdin_open: true
    networks:
      - wp-dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    networks:
      - wp-dev

volumes:
  db_data:

networks:
  wp-dev:
