services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8080:80
    networks:
      - wp-prod
    volumes:
      - web_code:/var/www/web:ro
      - wp_uploads:/var/www/web/app/uploads:ro
    depends_on:
      php-fpm:
        condition: service_healthy

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: production
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    volumes:
      - web_code:/var/www/web
      - wp_uploads:/var/www/web/app/uploads
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - wp-prod

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: db
      MARIADB_DATABASE: db
      MARIADB_USER: db
      MARIADB_PASSWORD: db
    volumes:
      - prod_db_data:/var/lib/mysql
    networks:
      - wp-prod
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-pdb"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  prod_db_data:
  wp_uploads:
  web_code:

networks:
  wp-prod:
