name: Build and Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend
        run: |
          docker build -f docker/node/Dockerfile -t ghcr.io/${{ github.repository_owner }}/frontend-final:latest .

      - name: Build PHP
        run: |
          docker build -f docker/php-fpm/Dockerfile -t ghcr.io/${{ github.repository_owner }}/php-production:latest --target production .

      - name: Build Nginx
        run: |
          docker build -f docker/nginx/Dockerfile -t ghcr.io/${{ github.repository_owner }}/nginx-production:latest .

      - name: Push Images
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/frontend-final:latest
          docker push ghcr.io/${{ github.repository_owner }}/php-production:latest
          docker push ghcr.io/${{ github.repository_owner }}/nginx-production:latest

      - name: Trigger Coolify Deployment
        run: |
          curl -X POST https://app.coolify.io/api/deploy/YOUR_APP_ID \
            -H "Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}"
